
# Data Keys
KEY_ID = 0
KEY_TYPE = 1
KEY_RECT_ID = 2
KEY_RECT_TEXT = 3

# Item Types
ITEM_TYPE_CIRCLE = "CIRCLE"
ITEM_TYPE_LABEL = "LABEL"
ITEM_TYPE_LABEL2 = "LABEL2"
ITEM_TYPE_RECTANGLE = "RECTANGLE"

# Editor Modes
MODE_SELECT = 'SELECT'
MODE_DRAWING_RECT = 'DRAWING_RECT'
MODE_ADD_CIRCLE = 'ADD_CIRCLE'
MODE_ADD_LABEL = 'ADD_LABEL'
MODE_ADD_LABEL2 = 'ADD_LABEL2'

# Alignment Directions
ALIGN_LEFT = 'left'
ALIGN_RIGHT = 'right'
ALIGN_TOP = 'top'
ALIGN_BOTTOM = 'bottom'

# Distribution Orientations
DISTRIBUTE_HORIZONTAL = 'horz'
DISTRIBUTE_VERTICAL = 'vert'

# Default Values
DEFAULT_SCENE_WIDTH = 1000
DEFAULT_SCENE_HEIGHT = 800
DEFAULT_RECT_WIDTH = 100
DEFAULT_RECT_HEIGHT = 100
CIRCLE_RADIUS = 25

# Colors
COLOR_BACKGROUND = "#333"
COLOR_HIGHLIGHT = "#4488FF"
COLOR_LABEL2 = "#00FFFF"
COLOR_TRANSPARENT_GREEN = (0, 255, 0, 100)
COLOR_TRANSPARENT_RED = (255, 0, 0, 50)

# Fonts
FONT_ARIAL = "Arial"
FONT_SIZE_NORMAL = 12
FONT_SIZE_LARGE = 14
FONT_SIZE_SMALL = 10